#!/usr/bin/env python3
"""Generate the registers and exports derived from use-case front-matter.

Reads the YAML front-matter of every file in use-cases/ and rebuilds:

- the generated tables in docs/mitre-attack-coverage.md,
- the metrics register table in docs/metrics-template.md,
- the use-case index at use-cases/README.md,
- the data-source onboarding table at docs/data-source-onboarding.md,
- Sigma exports in sigma/ (one file per embedded Sigma rule),
- the ATT&CK Navigator layer at docs/attack-navigator-layer.json.

Output is deterministic: rows are sorted by stable keys, so the files only
change when the front-matter or embedded Sigma rules change.

Usage:
    python3 scripts/generate_registers.py            # rewrite generated files
    python3 scripts/generate_registers.py --check    # exit 1 if files are stale
"""

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
USE_CASES_DIR = ROOT / "use-cases"
DOCS_DIR = ROOT / "docs"
SIGMA_DIR = ROOT / "sigma"

REQUIRED_FIELDS = (
    "id",
    "title",
    "domain",
    "severity",
    "attack_focus",
    "lifecycle_status",
    "mitre_tactics",
    "mitre_techniques",
    "mitre_mapping",
    "data_sources",
)
ALLOWED_DOMAINS = ("cloud", "email", "endpoint", "identity", "network")
ALLOWED_SEVERITIES = ("low", "medium", "high", "critical")
ALLOWED_LIFECYCLES = ("draft", "validated", "operational", "tuning-required", "retired")

# lifecycle_status -> coverage status shown in the ATT&CK coverage matrix
COVERAGE_BY_LIFECYCLE = {
    "draft": "Detect",
    "tuning-required": "Detect",
    "validated": "Alert",
    "operational": "Alert",
}

# Enterprise ATT&CK kill-chain order, using the UK spellings this library uses.
TACTIC_ORDER = (
    "Reconnaissance",
    "Resource Development",
    "Initial Access",
    "Execution",
    "Persistence",
    "Privilege Escalation",
    "Defence Evasion",
    "Credential Access",
    "Discovery",
    "Lateral Movement",
    "Collection",
    "Command and Control",
    "Exfiltration",
    "Impact",
)

FRONT_MATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
SIGMA_BLOCK_RE = re.compile(
    r"^###\s+Sigma rule\s*\n+```ya?ml\n(.*?)\n```", re.DOTALL | re.MULTILINE
)
GENERATED_NOTE = "generated by scripts/generate_registers.py"


def fail(errors):
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    sys.exit(1)


def tactic_sort_key(tactic):
    try:
        return (0, TACTIC_ORDER.index(tactic), tactic)
    except ValueError:
        return (1, 0, tactic)


def load_use_cases():
    """Parse and validate every use-case file. Returns a sorted list of dicts."""
    errors = []
    use_cases = []
    paths = sorted(
        p for p in USE_CASES_DIR.glob("UC-*.md") if p.name != "README.md"
    )
    if not paths:
        fail(["no use-case files found in use-cases/"])

    for path in paths:
        rel = path.relative_to(ROOT)
        text = path.read_text(encoding="utf-8")
        match = FRONT_MATTER_RE.match(text)
        if not match:
            errors.append(f"{rel}: missing YAML front-matter block")
            continue
        try:
            meta = yaml.safe_load(match.group(1))
        except yaml.YAMLError as exc:
            errors.append(f"{rel}: front-matter is not valid YAML: {exc}")
            continue
        if not isinstance(meta, dict):
            errors.append(f"{rel}: front-matter must be a YAML mapping")
            continue

        missing = [f for f in REQUIRED_FIELDS if not meta.get(f)]
        if missing:
            errors.append(f"{rel}: missing front-matter fields: {', '.join(missing)}")
            continue

        stem = path.stem
        if not stem.startswith(str(meta["id"]) + "-"):
            errors.append(f"{rel}: id {meta['id']!r} does not match the filename")
        if meta["domain"] not in ALLOWED_DOMAINS:
            errors.append(f"{rel}: domain must be one of {ALLOWED_DOMAINS}")
        if meta["severity"] not in ALLOWED_SEVERITIES:
            errors.append(f"{rel}: severity must be one of {ALLOWED_SEVERITIES}")
        if meta["lifecycle_status"] not in ALLOWED_LIFECYCLES:
            errors.append(f"{rel}: lifecycle_status must be one of {ALLOWED_LIFECYCLES}")

        mapping = meta["mitre_mapping"]
        if not isinstance(mapping, list) or not all(isinstance(m, dict) for m in mapping):
            errors.append(f"{rel}: mitre_mapping must be a list of mappings")
            continue
        for entry in mapping:
            entry_missing = [
                f
                for f in ("tactic", "technique_id", "technique_name", "detection_source")
                if not entry.get(f)
            ]
            if entry_missing:
                errors.append(
                    f"{rel}: mitre_mapping entry is missing: {', '.join(entry_missing)}"
                )
        mapped_tactics = {m.get("tactic") for m in mapping}
        mapped_techniques = {m.get("technique_id") for m in mapping}
        if mapped_tactics != set(meta["mitre_tactics"]):
            errors.append(f"{rel}: mitre_tactics does not match the tactics in mitre_mapping")
        if mapped_techniques != set(meta["mitre_techniques"]):
            errors.append(
                f"{rel}: mitre_techniques does not match the technique IDs in mitre_mapping"
            )

        sigma_rules = SIGMA_BLOCK_RE.findall(text)
        use_cases.append({"path": path, "stem": stem, "meta": meta, "sigma": sigma_rules})

    if errors:
        fail(errors)
    return use_cases


def replace_region(text, path, name, body):
    begin = f"<!-- BEGIN GENERATED: {name} -->"
    end = f"<!-- END GENERATED: {name} -->"
    if begin not in text or end not in text:
        fail([f"{path}: generated-region markers for {name!r} were not found"])
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    return pattern.sub(begin + "\n" + body + "\n" + end, text, count=1)


def severity_label(meta):
    label = meta["severity"].capitalize()
    note = meta.get("severity_note")
    return f"{label} ({note})" if note else label


def render_attack_matrix(use_cases):
    rows = []
    for uc in use_cases:
        if uc["meta"]["lifecycle_status"] == "retired":
            continue
        status = COVERAGE_BY_LIFECYCLE[uc["meta"]["lifecycle_status"]]
        for entry in uc["meta"]["mitre_mapping"]:
            rows.append(
                (
                    tactic_sort_key(entry["tactic"]),
                    entry["technique_id"],
                    uc["stem"],
                    entry["tactic"],
                    entry["technique_name"],
                    entry["detection_source"],
                    status,
                )
            )
    rows.sort()
    lines = [
        "| Tactic | Technique ID | Technique Name | Use Case ID | Detection Source | Coverage Status |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for _, tid, stem, tactic, tname, source, status in rows:
        lines.append(f"| {tactic} | {tid} | {tname} | {stem} | {source} | {status} |")
    return "\n".join(lines)


def render_heatmap(use_cases):
    counts = {}
    for uc in use_cases:
        if uc["meta"]["lifecycle_status"] == "retired":
            continue
        status = COVERAGE_BY_LIFECYCLE[uc["meta"]["lifecycle_status"]]
        for entry in uc["meta"]["mitre_mapping"]:
            tactic_counts = counts.setdefault(entry["tactic"], {"Detect": 0, "Alert": 0})
            tactic_counts[status] += 1
    lines = [
        "| Tactic | Detect | Alert | No Coverage | Gap rating |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    for tactic in sorted(counts, key=tactic_sort_key):
        detect = counts[tactic]["Detect"]
        alert = counts[tactic]["Alert"]
        total = detect + alert
        gap = "Low" if total >= 2 else ("Medium" if total == 1 else "High")
        lines.append(f"| {tactic} | {detect} | {alert} | 0 | {gap} |")
    return "\n".join(lines)


def render_use_case_coverage(use_cases):
    lines = [
        "| Use Case ID | Primary severity | Primary data sources | ATT&CK focus |",
        "| --- | --- | --- | --- |",
    ]
    for uc in use_cases:
        meta = uc["meta"]
        sources = ", ".join(meta["data_sources"])
        lines.append(
            f"| {uc['stem']} | {severity_label(meta)} | {sources} | {meta['attack_focus']} |"
        )
    return "\n".join(lines)


def render_metrics_register(use_cases):
    lines = [
        "| Use_Case_ID | Alert_Volume_This_Period | True_Positive_Count | False_Positive_Count | FP_Rate_Percent | MTTD_Minutes | MTTR_Hours | Escalation_Rate_Percent | Notes |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for uc in use_cases:
        lines.append(f"| {uc['stem']} |  |  |  |  |  |  |  |  |")
    return "\n".join(lines)


def render_use_case_index(use_cases):
    lines = [
        "# Use-case index",
        "",
        f"This index is {GENERATED_NOTE} from the front-matter in this directory. Do not edit it by hand.",
        "",
        "| Use case | Domain | Severity | MITRE techniques | Lifecycle status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for uc in use_cases:
        meta = uc["meta"]
        link = f"[{meta['id']} {meta['title']}]({uc['path'].name})"
        techniques = ", ".join(meta["mitre_techniques"])
        lines.append(
            f"| {link} | {meta['domain']} | {severity_label(meta)} | {techniques} | {meta['lifecycle_status']} |"
        )
    lines += [
        "",
        "## By domain",
        "",
        "| Domain | Use cases |",
        "| --- | --- |",
    ]
    by_domain = {}
    for uc in use_cases:
        by_domain.setdefault(uc["meta"]["domain"], []).append(uc["meta"]["id"])
    for domain in sorted(by_domain):
        lines.append(f"| {domain} | {', '.join(by_domain[domain])} |")
    lines += [
        "",
        "See [docs/data-source-onboarding.md](../docs/data-source-onboarding.md) for the telemetry each use case requires.",
        "",
    ]
    return "\n".join(lines)


def render_data_source_onboarding(use_cases):
    sources = {}
    for uc in use_cases:
        for source in uc["meta"]["data_sources"]:
            sources.setdefault(source, []).append(uc["meta"]["id"])
    lines = [
        "# Data source onboarding",
        "",
        f"This table is {GENERATED_NOTE} from the `data_sources` front-matter field across `use-cases/`. Do not edit it by hand.",
        "",
        "Use it to confirm which telemetry must be onboarded before adopting the library. A source required by more use cases gives more detection value once onboarded. The minimum fields for each source are listed in the Required data sources table of each use case.",
        "",
        "| Data source | Required by | Use cases |",
        "| --- | ---: | --- |",
    ]
    for source in sorted(sources, key=str.lower):
        ids = sources[source]
        lines.append(f"| {source} | {len(ids)} | {', '.join(ids)} |")
    lines.append("")
    return "\n".join(lines)


def render_navigator_layer(use_cases):
    techniques = {}
    for uc in use_cases:
        if uc["meta"]["lifecycle_status"] == "retired":
            continue
        for entry in uc["meta"]["mitre_mapping"]:
            techniques.setdefault(entry["technique_id"], []).append(uc["meta"]["id"])
    max_score = max((len(v) for v in techniques.values()), default=1)
    layer = {
        "name": "SOC Use Cases and Playbooks coverage",
        "versions": {"attack": "16", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "Technique coverage of the SOC Use Cases and Playbooks library. "
            "Generated by scripts/generate_registers.py from use-case front-matter. "
            "Do not edit by hand."
        ),
        "sorting": 0,
        "techniques": [
            {
                "techniqueID": tid,
                "score": len(ids),
                "comment": "Covered by " + ", ".join(sorted(ids)),
                "enabled": True,
                "showSubtechniques": True,
            }
            for tid, ids in sorted(techniques.items())
        ],
        "gradient": {
            "colors": ["#ffe766", "#8ec843"],
            "minValue": 1,
            "maxValue": max_score,
        },
        "legendItems": [],
        "metadata": [],
    }
    return json.dumps(layer, indent=2) + "\n"


def sigma_outputs(use_cases):
    outputs = {}
    for uc in use_cases:
        for index, rule in enumerate(uc["sigma"]):
            suffix = "" if len(uc["sigma"]) == 1 else f"-{index + 1}"
            name = f"{uc['stem'].lower()}{suffix}.yml"
            header = (
                f"# Exported from use-cases/{uc['path'].name}\n"
                f"# This file is {GENERATED_NOTE}. Edit the use case, not this file.\n"
            )
            outputs[SIGMA_DIR / name] = header + rule + "\n"
    return outputs


def build_outputs():
    use_cases = load_use_cases()

    coverage_path = DOCS_DIR / "mitre-attack-coverage.md"
    coverage_text = coverage_path.read_text(encoding="utf-8")
    coverage_text = replace_region(
        coverage_text, coverage_path, "attack-matrix", render_attack_matrix(use_cases)
    )
    coverage_text = replace_region(
        coverage_text, coverage_path, "heatmap", render_heatmap(use_cases)
    )
    coverage_text = replace_region(
        coverage_text, coverage_path, "use-case-coverage", render_use_case_coverage(use_cases)
    )

    metrics_path = DOCS_DIR / "metrics-template.md"
    metrics_text = replace_region(
        metrics_path.read_text(encoding="utf-8"),
        metrics_path,
        "metrics-register",
        render_metrics_register(use_cases),
    )

    outputs = {
        coverage_path: coverage_text,
        metrics_path: metrics_text,
        USE_CASES_DIR / "README.md": render_use_case_index(use_cases),
        DOCS_DIR / "data-source-onboarding.md": render_data_source_onboarding(use_cases),
        DOCS_DIR / "attack-navigator-layer.json": render_navigator_layer(use_cases),
    }
    outputs.update(sigma_outputs(use_cases))

    stale_sigma = [
        p for p in SIGMA_DIR.glob("*.yml") if p not in outputs
    ] if SIGMA_DIR.is_dir() else []
    return outputs, stale_sigma


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write anything; exit 1 if any generated file is stale",
    )
    args = parser.parse_args()

    outputs, stale_sigma = build_outputs()

    if args.check:
        stale = [
            path
            for path, content in sorted(outputs.items())
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        stale.extend(stale_sigma)
        if stale:
            for path in stale:
                print(f"STALE: {path.relative_to(ROOT)}", file=sys.stderr)
            print(
                "Generated files are out of date. Run: python3 scripts/generate_registers.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"All {len(outputs)} generated files are up to date.")
        return

    SIGMA_DIR.mkdir(exist_ok=True)
    for path, content in sorted(outputs.items()):
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    for path in stale_sigma:
        path.unlink()
        print(f"removed stale {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
